---
flighdeck_motd_name: httpd 2.4

flightdeck_groups:
  - name: "flightdeck"

flightdeck_users:
  - name: "flightdeck"
    group: "flightdeck"
    home: "/var/www"

flightdeck_root_prompt: '\u@flightdeck-httpd-2.4:\w# '
flightdeck_user_prompt: '\u@flightdeck-httpd-2.4:\w$ '

flightdeck_motd_links:
  - name: 'Code & docs'
    url: 'https://github.com/ten7/flightdeck-httpd-2.4'
  - name: ' Learn more'
    url: 'https://flightdeck.ten7.com/'

flightdeck_init_commands: |
  if [ -f "/ansible/init.yml" ]; then
    if [ -n "${FLIGHTDECK_CONFIG}" ]; then
      config_file=$(mktemp "${TMPDIR:-/tmp/}$(basename $0).XXXXXXXXXXXX")
      echo "$FLIGHTDECK_CONFIG" | base64 -d > $config_file
      ansible-playbook -i /etc/ansible/hosts -i /ansible/inventories/all.ini -e "@${config_file}" /ansible/init.yml
    elif [ -f "${FLIGHTDECK_CONFIG_FILE}" ]; then
      ansible-playbook -i /etc/ansible/hosts -i /ansible/inventories/all.ini -e "@${FLIGHTDECK_CONFIG_FILE}" /ansible/init.yml
    elif [ -f "/config/httpd/flightdeck-httpd.yml" ]; then
      ansible-playbook -i /etc/ansible/hosts -i /ansible/inventories/all.ini -e "@/config/httpd/flightdeck-httpd.yml" /ansible/init.yml
    else
      ansible-playbook -i /etc/ansible/hosts -i /ansible/inventories/all.ini /ansible/init.yml
    fi
  fi

flightdeck_run_commands: |
  if [ -f "/ansible/run.yml" ]; then
    if [ -n "${FLIGHTDECK_CONFIG}" ]; then
      config_file=$(mktemp "${TMPDIR:-/tmp/}$(basename $0).XXXXXXXXXXXX")
      echo "$FLIGHTDECK_CONFIG" | base64 -d > $config_file
      ansible-playbook -i /etc/ansible/hosts -i /ansible/inventories/all.ini -e "@${config_file}" /ansible/run.yml
    elif [ -f "${FLIGHTDECK_CONFIG_FILE}" ]; then
      ansible-playbook -i /etc/ansible/hosts -i /ansible/inventories/all.ini -e "@${FLIGHTDECK_CONFIG_FILE}" /ansible/run.yml
    elif [ -f "/config/httpd/flightdeck-httpd.yml" ]; then
      ansible-playbook -i /etc/ansible/hosts -i /ansible/inventories/all.ini -e "@/config/httpd/flightdeck-httpd.yml" /ansible/run.yml
    else
      ansible-playbook -i /etc/ansible/hosts -i /ansible/inventories/all.ini /ansible/run.yml
    fi
  fi
