---
# We only check for the directory's existance as on Compose, it may be
# owned by root, and we won't have the authority to chown. On k8s, this
# should be accomplished by the container build scripts.
- name: Ensure vhost directories exist
  file:
    path: "{{ item.docroot }}"
    state: directory
  loop: "{{ flightdeck_httpd.vhosts | default(flightdeck_httpd_default_vhosts) }}"
  when:
    - item.docroot is defined
- name: Configure httpd vhosts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "flightdeck"
    group: "flightdeck"
    mode: "u=rw,g=r,o="
  loop:
    - src: "templates/httpd.conf"
      dest: "/etc/apache2/httpd.conf"
    - src: "templates/mpm.conf"
      dest: "/etc/apache2/conf.d/mpm.conf"
    - src: "templates/000_default.conf"
      dest: "/etc/apache2/sites.d/000_default.conf"
- name: Update initial directory
  lineinfile:
    path: "/var/www/.bashrc"
    regexp: "^cd \\$HOME$"
    line: "cd {{ flightdeck_httpd.vhosts[0].docroot | default('$HOME') }}"
    state: present
